# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200526_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCategory',
        ),
    ]
